module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{html,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        black: "var(--black)",
        "gray-0": "var(--gray-0)",
        "gray-1": "var(--gray-1)",
        "gray-2": "var(--gray-2)",
        "gray-3": "var(--gray-3)",
        "gray-4": "var(--gray-4)",
        "gray-5": "var(--gray-5)",
        green: "var(--green)",
        pink: "var(--pink)",
        "purple-1": "var(--purple-1)",
        "purple-2": "var(--purple-2)",
        "purple-3": "var(--purple-3)",
        "purple-4": "var(--purple-4)",
        "purple-5": "var(--purple-5)",
        "purple-6": "var(--purple-6)",
        white: "var(--white)",
        "yellow-1": "var(--yellow-1)",
        "yellow-2": "var(--yellow-2)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "base-150": "var(--base-150)",
        basewhite: "var(--basewhite)",
      },
      fontFamily: {
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        "bold-12": "var(--bold-12-font-family)",
        "bold-14": "var(--bold-14-font-family)",
        "bold-16": "var(--bold-16-font-family)",
        "bold-18": "var(--bold-18-font-family)",
        "bold-20": "var(--bold-20-font-family)",
        "bold-24": "var(--bold-24-font-family)",
        "bold-32": "var(--bold-32-font-family)",
        "bold-40": "var(--bold-40-font-family)",
        "medium-12": "var(--medium-12-font-family)",
        "medium-14": "var(--medium-14-font-family)",
        "medium-16": "var(--medium-16-font-family)",
        "medium-18": "var(--medium-18-font-family)",
        "medium-20": "var(--medium-20-font-family)",
        "medium-24": "var(--medium-24-font-family)",
        "regular-12": "var(--regular-12-font-family)",
        "regular-14": "var(--regular-14-font-family)",
        "regular-16": "var(--regular-16-font-family)",
        "regular-18": "var(--regular-18-font-family)",
        "regular-20": "var(--regular-20-font-family)",
        "regular-24": "var(--regular-24-font-family)",
        "semibold-12": "var(--semibold-12-font-family)",
        "semibold-14": "var(--semibold-14-font-family)",
        "semibold-16": "var(--semibold-16-font-family)",
        "semibold-18": "var(--semibold-18-font-family)",
        "semibold-20": "var(--semibold-20-font-family)",
        "semibold-24": "var(--semibold-24-font-family)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
