import "@/src/styles/tailwind.css";
import "@/src/styles/globals.css";
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function enableMocking() {
  if (process.env.NODE_ENV !== 'development') {
    return;
  }

  const { setUpMocks } = await import('@/src/mocks/browser');
  return setUpMocks();
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  await enableMocking();

  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
