name: "PR Auto Assign Reviewers"

on:
  pull_request:
    types: [opened, reopened] # PR이 열리거나 다시 열릴 때 실행

jobs:
  add-reviews:
    runs-on: ubuntu-latest # 실행 환경
    steps:
      - name: Checkout repository # 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Install yq # yq 설치 (필요한 경우)
        run: |
          sudo apt-get update && sudo apt-get install -y yq

      - name: Load Team Members from Config
        id: load-config
        run: |
          TEAM_MEMBERS=$(yq e '.teamMembers[]' .github/auto_assign.yml | grep -v "^${{ github.actor }}$")
          echo "REVIEWERS=$(echo $TEAM_MEMBERS | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Assign PR Creator as Assignee
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto_assign.yml # 설정 파일 로드
          add-assignees: true # PR 작성자를 Assignee로 지정
          add-reviewers: true # 리뷰어 추가
          reviewers: ${{ env.REVIEWERS }} # PR 작성자를 제외한 나머지 팀원 2명 지정
          number-of-reviewers: 2 # 랜덤으로 2명의 리뷰어 선택
